### ISSUE TITLE
Avail for GM not for Players

### ISSUE THREAD

**Issue by ngPescado** [RaySSharma/fvtt-rolltable-buttons#10]
Disabled all modules except Rolltable for troubleshooting purposes. Using **Foundry 0.7.9** with **DnD5e 1.2.4** and **Rolltable Buttons 1.2.2**. Tables are avail for _players_ as _observers_ (and usable with macros). _GM_ clicks on Rolltable button and it works as intended. Player login (_Trusted_) clicks on button and nothing happens (button animation but no pop out). Changing permissions on tables to _Owner_ for players does not change the scenario. Thoughts?

**Comment by RaySSharma** [comment]
I was misinterpreting how permissions were handled for tables/folders. v1.2.3 should fix it (and probably #9 as well)
