### ISSUE TITLE
Does Not Initiate a Roll

### ISSUE THREAD

**Issue by KevinRichard-GM** [RaySSharma/fvtt-rolltable-buttons#11]
I open the list of tables to roll on from the chat button but when I click on any of the tables loaded in the screen nothing happens. A roll is not initiated. I've opened up the table and made the roll on the table tab and they work fine.

I reported this issue previously but it was recently closed.

**Comment by RaySSharma** [comment]
Can you give more info? When you open the console (F12), does it print anything when pressing the RTB icon?

**Comment by KevinRichard-GM** [comment]
Uncaught SyntaxError: Unexpected end of input

**Comment by RaySSharma** [comment]
What version of the package are you using?

**Comment by KevinRichard-GM** [comment]
Using the most recent stable release of Foundry VTT 0.7.9 hosted on The Forge. I updated your module to the latest version 1.2.3

**Comment by RaySSharma** [comment]
I'm not sure, do you have info on the specific table? What are the entries, rolling ranges, permission levels, etc?

**Comment by KevinRichard-GM** [comment]
I made a table with my PCs in it (4 entities), 1d4, All Players OWNER. Along with an assortment of other tables loaded from compendiums (Bard Songs, City Street Encounters) with no permission specified.

**Comment by KevinRichard-GM** [comment]
{
  "_id": "LHq83fA6RMeYRiLr",
  "name": "PCs",
  "sort": 100001,
  "flags": {
    "exportSource": {
      "world": "abomination-vaults",
      "system": "pf2e",
      "coreVersion": "0.7.9",
      "systemVersion": "1.15.0.5631"
    }
  },
  "img": "icons/svg/d20-grey.svg",
  "description": "A random table created from the contents of the PCs Folder.",
  "results": [
    {
      "_id": "shQxmAWMWY6WwIgA",
      "flags": {},
      "type": 1,
      "text": "Cairo",
      "img": "https://assets.forge-vtt.com/5f98d64fd798a80683239063/Abomination%20Vaults/Portraits%20-%20PCs/portrait.Cairo%2C%20full%20body%20v10%20(2048px).webp",
      "collection": "Actor",
      "resultId": "ybTQJYJ9gPdozsv7",
      "weight": 1,
      "range": [
        1,
        1
      ],
      "drawn": false
    },
    {
      "_id": "9mUSvgaYVYSFR1cx",
      "flags": {},
      "type": 1,
      "text": "Crowley",
      "img": "https://assets.forge-vtt.com/5f98d64fd798a80683239063/Abomination%20Vaults/Portraits%20-%20PCs/portrait.Crowley%20v11%20(2048px).webp",
      "collection": "Actor",
      "resultId": "ISyh2JzC4XloCHPj",
      "weight": 1,
      "range": [
        2,
        2
      ],
      "drawn": false
    },
    {
      "_id": "ZnGKIrXu2QJxdC0V",
      "flags": {},
      "type": 1,
      "text": "Papillion",
      "img": "https://assets.forge-vtt.com/5f98d64fd798a80683239063/Abomination%20Vaults/Portraits%20-%20PCs/portrait.Papillon%20v2%20(2048px).webp",
      "collection": "Actor",
      "resultId": "yyTrQREvekfQYCaR",
      "weight": 1,
      "range": [
        3,
        3
      ],
      "drawn": false
    },
    {
      "_id": "x6QJN6nfRaW4QOiY",
      "flags": {},
      "type": 1,
      "text": "Rubyfruit Rootytoot",
      "img": "https://assets.forge-vtt.com/5f98d64fd798a80683239063/Abomination%20Vaults/Portraits%20-%20PCs/portrait.Rubyfruit%20Rootytoot%20v4%20(2048px).webp",
      "collection": "Actor",
      "resultId": "HSxPrGeN84JeXbiw",
      "weight": 1,
      "range": [
        4,
        4
      ],
      "drawn": false
    }
  ],
  "formula": "1d4",
  "replacement": true,
  "displayRoll": true
}

**Comment by RaySSharma** [comment]
I tracked down the issue to something strange happening with Handlebars under the hood. It seemed to be tied to operating system -- I'm guessing you're on Windows? Hopefully it is fixed now with v1.2.4. I'll close this thread when you give me the go-ahead.

**Comment by KevinRichard-GM** [comment]
Yes, Windows 10.

**Comment by KevinRichard-GM** [comment]
Works now, thanks.
