### ISSUE TITLE
Rolltable button does not show up in 0.7.4 of foundry

### ISSUE THREAD

**Issue by joeschnurr** [RaySSharma/fvtt-rolltable-buttons#2]
I am currently using the module in 0.6.6 with no issue.  However in 0.7.4 the button is not visible next to the dice button.

**Comment by rmasoni** [comment]
Same on `0.7.5`.

**Comment by montver** [comment]
Same in 0.7.5

**Comment by RaySSharma** [comment]
Fixed JS to allow button to show up in 0.7.4+

**Comment by joeschnurr** [comment]
It doesn't seem to update?  maybe it hasn't been pushed to foundry yet?
