### ISSUE TITLE
Updated to the newest version and no button

### ISSUE THREAD

**Issue by Nuku** [RaySSharma/fvtt-rolltable-buttons#3]
![image](https://user-images.githubusercontent.com/886729/97117229-87552180-16bf-11eb-9ea8-590b9b39d7f6.png)

**Comment by RaySSharma** [comment]
I messed up the update, the tag was accidentally pointing at an old commit. v1.1.7 now points at [#aaaca65](https://github.com/RaySSharma/fvtt-rolltable-buttons/commit/aaaca65de7d2dff5e9355df7d42c21d60f1e2fd7). I tested it by downloading it through FVTT, it works!
