### ISSUE TITLE
Not Initiating Rolls

### ISSUE THREAD

**Issue by KevinRichard-GM** [RaySSharma/fvtt-rolltable-buttons#6]
Roll tables show up in the list when you click the button but clicking on the table in the popout doesn't generate a roll on the associated table.

Roll tables work fine if used from the Roll Table tab.

**Comment by DieterKosken** [comment]
I have a solution for it. 

Looks like something got wonky in the template file for button push. 

in the file modules\rolltable-buttons\templates\rolltable-menu.html

on line 6, got to replace entire line with:

`<button onclick="RTB.draw(&quot;{{{this.name}}}&quot;)" class="RTB-entry">{{this.name}}</button>`

Not sure this breaks something else of if its even the same issue on line 4 but this fixed it for me.

**Comment by RaySSharma** [comment]
I'm not sure what the initial issue was here. I tried @DieterKosken's fix, but that ended up breaking tables/folders with quotes in the name. Tentatively closing for now.
