### ISSUE TITLE
Small request

### ISSUE THREAD

**Issue by jeffhafer** [RaySSharma/fvtt-rolltable-buttons#7]
Great idea. Works fine for me but could you make the font size a little smaller? Maybe a checkbox or a button size picker for users to decide how big they want them.

I edited the CSS file for myself and can get a lot more tables in a small area:

#RTB-menu .RTB-entry {
    background-color: rgba(0,0,0,0.8);
    color: #f0f0e0;
    padding: 2px;   /*padding: 10px;*/
    font-size: 11px; /*font-size: 20px;*/
    line-height: 10px; /*Added*/
    margin-bottom: 1px; /*margin-bottom: 5px;*/
    border: 1px solid #111111;
    cursor: pointer;
}

Thanks,
Jeff.

**Comment by RaySSharma** [comment]
Made text significantly smaller in v1.2.0, though not quite as small as you had it. Thanks!
