### ISSUE TITLE
Not rolling if all results the same

### ISSUE THREAD

**Issue by jangowolf** [RaySSharma/fvtt-rolltable-buttons#8]
![2021-05-14 23_07_20-Window](https://user-images.githubusercontent.com/51888805/118346434-401e6900-b509-11eb-9af9-edc3478b14d2.png)
I'm having trouble getting all the results to show up in chat when I roll using this module. I have tried changing the weight and range in the rolltable but the result is mostly the same. Either one thing shows up or nothing.

**Comment by RaySSharma** [comment]
Fixed with v1.2.2
