### ISSUE TITLE
Clicking does nothing.

### ISSUE THREAD

**Issue by Nuku** [RaySSharma/fvtt-rolltable-buttons#9]
So here I am.
![image](https://user-images.githubusercontent.com/886729/118407319-25491300-b635-11eb-9951-5d773ffb5741.png)
Perfectly normal table. I click Hero Points, nothing happens.
If I roll the table manually, just to be sure, it works fine.

**Comment by RaySSharma** [comment]
Hopefully fixed by v1.2.3
